---
- name: Ensure existence of config dir
  ansible.builtin.file:
    path: "{{ config_dir }}"
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    state: directory


- name: Ensure existence of logs dir
  ansible.builtin.file:
    path: "{{ _logs_dir }}"
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    state: directory

- name: Ensure existence of data dir
  ansible.builtin.file:
    path: "{{ _data_dir }}"
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    state: directory

- name: Ensure existence of provisioning dir
  ansible.builtin.file:
    path: "{{ _provisioning_dir }}"
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    state: directory

- name: Ensure existence of plugins dir
  ansible.builtin.file:
    path: "{{ _plugins_dir }}"
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    state: directory

