---

- name: "Ensure that directories are existed"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    mode: '0775'
  with_items:
    - "{{ install_dir }}"
    - "{{ config_dir }}"
    - "{{ pid_file_dir }}"
    - "{{ log_dir }}"
    - "{{ data_dir }}"
    - "{{ provisioning_cfg_dir }}"
    - "{{ plugins_dir }}"

- name: "Download Grafana archive"
  ansible.builtin.get_url:
    url: "https://dl.grafana.com/oss/release/grafana-{{ grafana_version }}.linux-amd64.tar.gz"
    dest: "/tmp/grafana-{{ grafana_version }}.linux-amd64.tar.gz"
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    mode: "0644"
  register: archive_tmp

- name: "Extract Grafana archive"
  ansible.builtin.unarchive:
    src: "{{ archive_tmp.dest }}"
    dest: "{{ install_dir }}"
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    mode: '0775'
    remote_src: true
    extra_opts:
      - --strip-components
      - '1'

- name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
  ansible.builtin.file:
    path: "{{ pid_file_dir }}/grafana-server.pid"
    state: touch
    mode: "0755"
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"

- name: "Copy ini file"
  ansible.builtin.copy:
    src: files/grafana.ini
    dest: "{{ config_dir }}"
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    mode: "0660"

- name: "Move grafana cli wrapper"
  ansible.builtin.copy:
    src: /usr/share/grafana/packaging/wrappers/{{ item }}
    dest: /usr/sbin/{{ item }}
    remote_src: true
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    mode: "0755"
  with_items:
    - grafana-cli
    - grafana-server

- name: "Create systemd service unit"
  notify: "(Re)start and enable Grafana"
  ansible.builtin.template:
    src: grafana-server.service.j2
    dest: /etc/systemd/system/grafana-server.service
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    mode: "0660"
