---

- name: Create installation directory
  ansible.builtin.file:
    path: "{{ install_dir }}"
    state: directory
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    mode: '0775'

- name: "Download Grafana archive"
  ansible.builtin.get_url:
    url: "https://dl.grafana.com/oss/release/grafana-{{ grafana_version }}.linux-amd64.tar.gz"
    dest: "/tmp/grafana-{{ grafana_version }}.linux-amd64.tar.gz"
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    mode: "0644"
  register: archive_tmp

- name: Extract Grafana archive
  ansible.builtin.unarchive:
    src: "{{ archive_tmp.dest }}"
    dest: "{{ install_dir }}"
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    mode: '0775'
    remote_src: true
    extra_opts:
      - --strip-components
      - '1'
