---
- name: "Create Grafana system group"
  ansible.builtin.group:
    name: grafana
    system: true
    state: present

- name: "Create Grafana system user"
  ansible.builtin.user:
    name: grafana
    group: grafana
    system: true
    shell: "/sbin/nologin"
    create_home: false
    state: present

- name: "Install Grafana deb package"
  block:
    - name: "Check Grafana version"
      changed_when: false
      ansible.builtin.command:
        cmd: "grafana-server --version"
      register: grafana_ver

    - name: "Assert version correctness"
      ansible.builtin.assert:
        that: "grafana_ver.stdout is regex('{{ grafana_version }}')"
        success_msg: "grafana version {{ grafana_version }} is installed and working"
        fail_msg: "grafana version {{ grafana_version }} is not installed or not working correctly"

  rescue:
    - name: "Install Grafana from deb package"
      when: install_type == "deb_download"
      ansible.builtin.include_tasks: install_package.yml

    - name: "Install Grafana from tar archive"
      when: install_type == "direct_download"
      ansible.builtin.include_tasks: install_archive.yml

- name: "Flush handlers"
  ansible.builtin.meta: "flush_handlers"
