---
- name: "Create Alertmanager group"
  ansible.builtin.group:
    name: alertmanager
    state: present

- name: "Create Alertmanager system user"
  ansible.builtin.user:
    name: alertmanager
    group: alertmanager
    system: true
    shell: "/sbin/nologin"
    create_home: true
    home: "{{ alertmanager_dir }}"

- name: "Download Alertmanager binary"
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager_version }}/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"
    dest: "/tmp/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"

- name: "Unpack Alertmanager binaries"
  ansible.builtin.unarchive:
    src: "/tmp/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"
    dest: "{{ alertmanager_dir }}"
    creates: "{{ alertmanager_dir }}/alertmanager-{{ alertmanager_version }}.linux-amd64"
    remote_src: true

- name: "Cleanup downloaded file"
  ansible.builtin.file:
    path: "/tmp/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"
    state: absent

- name: "Move alertmanager binary"
  ansible.builtin.copy:
    src: "{{ alertmanager_dir }}/alertmanager-{{ alertmanager_version }}.linux-amd64/alertmanager"
    dest: "/usr/local/bin/alertmanager"
    mode: 0755
    owner: alertmanager
    group: alertmanager
    remote_src: true
