---

- name: Ensure that directories are existed
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    mode: '0775'
  with_items:
    - {{ install_dir }}
    - {{ config_dir }}
    - {{ pid_file_dir }}
    - {{ log_dir }}
    - {{ data_dir }}
    - {{ provisioning_cfg_dir }}

- name: "Download Grafana archive"
  ansible.builtin.get_url:
    url: "https://dl.grafana.com/oss/release/grafana-{{ grafana_version }}.linux-amd64.tar.gz"
    dest: "/tmp/grafana-{{ grafana_version }}.linux-amd64.tar.gz"
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    mode: "0644"
  register: archive_tmp

- name: Extract Grafana archive
  ansible.builtin.unarchive:
    src: "{{ archive_tmp.dest }}"
    dest: "{{ install_dir }}"
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    mode: '0775'
    remote_src: true
    extra_opts:
      - --strip-components
      - '1'
