---
- name: "Include grafana installation tasks"
  ansible.builtin.include_tasks: install_deb_graf.yml

- name: "Include user creation tasks"
  ansible.builtin.include_tasks: user.yml

- name: "Configure Grafana"
  ansible.builtin.include_tasks: configuration.yml