---
- name: "Run | build and start the `docker-compose` stack"
  tags: [ monitoring, monitoring-run ]
  changed_when: false
  community.docker.docker_compose:
    tls_hostname: localhost
    project_src: "{{ mon_root_dir }}"
    files:
      - docker-compose.yaml
    build: true
    state: present
    restarted: "{{ monitoring_restarted }}"


- name: "Run | reload Prometheus configuration"
  register: this
  until: this is ansible.builtin.success
  retries: 3
  delay: 3
  ansible.builtin.uri:
    url: "http://localhost:9090/-/reload"
    method: POST
    status_code: 200


- name: "Run | reload AlertManager configuration"
  tags: [ monitoring, monitoring-run ]
  register: this
  until: this is ansible.builtin.success
  retries: 3
  delay: 3
  ansible.builtin.uri:
    url: "http://localhost:9093/-/reload"
    method: POST
    status_code: 200


- name: "Run | create Grafana users"
  tags: [ monitoring, monitoring-run ]
  no_log: true
  register: this
  until: this is ansible.builtin.success
  retries: 5
  delay: 3
  changed_when: "'User created' in this.content"
  failed_when:  # a list is equivalent to chained ANDs here
    - "'already exists' not in this.content"
    - "'User created' not in this.content"
  loop: "{{ secrets.grafana.users }}"
  ansible.builtin.uri:
    method: "POST"
    url: "http://localhost:3000/api/admin/users"
    headers:
      accept: "application/json"
      Content-Type: "application/json"
    return_content: true
    force_basic_auth: true
    user: "admin"
    password: "{{ secrets.grafana.admin_password }}"
    body_format: "json"
    body:
      email: "{{ item.email }}"
      login: "{{ item.login }}"
      name: "{{ item.name }}"
      orgId: 0
      password: "{{ item.password }}"


- name: "Run | reload Grafana provisioned configurations"
  tags: [ monitoring, monitoring-run ]
  loop:
    - "dashboards"
    - "datasources"
    - "plugins"
  ansible.builtin.uri:
    url: "http://localhost:3000/api/admin/provisioning/{{ item }}/reload"
    method: POST
    force_basic_auth: true
    user: admin
    password: "{{ secrets.grafana.admin_password }}"
    status_code: 200
