---
- name: "Create or update a Grafana user"
  community.grafana.grafana_user:
    url: "http://127.0.0.1:3000"
    url_username: "admin"
    url_password: "{{ url_password }}"
    name: "{{ user_name }}"
    email: "{{ user_email }}"
    login: "{{ user_login }}"
    password: "{{ user_password }}"
    is_admin: true
    state: present
