---
- name: Converge
  hosts: all
  vars:
    go_version: "1.21.5"
  pre_tasks:
    - name: "Check if the Go installation is of the required version"
      register: go_version_string
      failed_when: false
      changed_when: false
      environment:
        PATH: "/usr/local/go/bin:{{ ansible_env.PATH }}"
      ansible.builtin.command:
        cmd: "go version"

    - name: "Ensure that the destination directory exists - '/usr/local/go/bin'"
      when: "go_version not in go_version_string.stdout"
      ansible.builtin.file:
        path: "/usr/local/go/bin"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: "Delete the previous Go installation under '/usr/local/go/bin/'"
      when: "go_version not in go_version_string.stdout"
      register: cleanout
      changed_when: cleanout.stdout
      ansible.builtin.shell:
        cmd: "/bin/rm -rf --preserve-root /usr/local/go/bin/*"

    - name: "Download and unarchive Golang release v{{ go_version }}"
      when: "go_version not in go_version_string.stdout"
      ansible.builtin.unarchive:
        src: "https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz"
        dest: "/usr/local/"
        remote_src: true

    - name: "Ensure that Golang binaries are in the PATH (via /etc/profile)"
      when: "go_version not in go_version_string.stdout"
      ansible.builtin.lineinfile:
        path: /etc/profile
        line: "export PATH=$PATH:/usr/local/go/bin"
        state: present

    - name: "Check that Golang binary is accessible and functional"
      changed_when: false
      environment:
        PATH: "/usr/local/go/bin:{{ ansible_env.PATH }}"
      ansible.builtin.command:
        cmd: go version

  roles:
    - role: genlab.grafana
      grafana_version: 11.5.0
      prometheus_version: 3.1.0
      alertmanager_version: 0.28.0
      prometheus_db_dir: "/home/prometheus"
      grafana_db_dir: "/home/grafana"
      alertmanager_dir: "/home/altmanager"

