---
- name: Converge
  hosts: all

  pre_tasks:
    - name: "Create Grafana system group"
      ansible.builtin.group:
        name: grafana
        system: true
        state: present

    - name: "Create Grafana system user"
      ansible.builtin.user:
        name: grafana
        group: "{{ grafana_group }}"
        system: true
        shell: "/sbin/nologin"
        create_home: false

    - name: "Create Prometheus system group"
      ansible.builtin.group:
        name: prometheus
        system: true
        state: present

    - name: "Create Prometheus system user"
      ansible.builtin.user:
        name: prometheus
        group: prometheus
        system: true
        shell: "/sbin/nologin"
        create_home: false

    - name: "Create Prometheus configuration directory"
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: prometheus
        group: prometheus
        mode: 0755
      loop: 
        - "/var/lib/prometheus"
        - "/etc/prometheus/"

    - name: "Download Prometheus binary"
      ansible.builtin.get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v3.1.0/prometheus-3.1.0.linux-amd64.tar.gz"
        dest: "/tmp/prometheus-3.1.0.linux-amd64.tar.gz"

    - name: "Unpack Prometheus binaries"
      ansible.builtin.unarchive:
        src: "/tmp/prometheus-3.1.0.linux-amd64.tar.gz"
        dest: "/tmp"
        creates: "/tmp/prometheus-3.1.0.linux-amd64"
        remote_src: true

    - name: "Move official prometheus and promtool binaries"
      ansible.builtin.copy:
        src: "/tmp/prometheus-3.1.0.linux-amd64/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        mode: 0755
        owner: prometheus
        group: prometheus
        remote_src: true
      with_items:
        - prometheus
        - promtool

    - name: "Create systemd service unit"
      ansible.builtin.template:
        src: prometheus.service.j2
        dest: /etc/systemd/system/prometheus.service
        owner: root
        group: root
        mode: 0660

    - name: "Make sure that the timer units are enabled and started"
      become: true
      ansible.builtin.systemd:
        name: prometheus.service
        state: started
        enabled: true
        daemon_reload: true

  roles:
    - role: genlab.grafana
      grafana_version: 11.5.0
