---
- name: Converge
  hosts: all

  pre_tasks:
    - name: "Create Grafana system group"
      ansible.builtin.group:
        name: grafana
        system: true
        state: present

    - name: "Create Grafana system user"
      ansible.builtin.user:
        name: grafana
        group: grafana
        system: true
        shell: "/sbin/nologin"
        create_home: false

  roles:
    # kics-scan ignore-block
    - role: genlab.grafana
      grafana_version: 11.5.0
      admin_api_username: "admin"
      admin_api_password: "admin"
      password: "test"
      user_name: "test"
      user_login: "test"
      user_password: "test"
      user_email: "test@mail.ru"
