# kics-scan disable=b710fc6abe5f032dde4691b44d52b199ac371a_334a9a
---
- name: Verify
  hosts: all
  gather_facts: false
  any_errors_fatal: true

  tasks:

    - name: "Include default vars"
      ansible.builtin.include_vars:
        dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/"
        extensions: [ 'yml' ]

    - name: "Check if Grafana is installed"
      changed_when: false
      ansible.builtin.command: "grafana-server -v"
      register: grafana_installed_version

    - name: "Check Grafana version"
      ansible.builtin.assert:
        that: "grafana_installed_version.stdout is regex('{{ grafana_version }}')"
        success_msg: "grafana version {{ grafana_version }} is installed and working"
        fail_msg: "grafana version {{ grafana_version }} is not installed or not working correctly"

    - name: "Check if Grafana login page is reachable"
      retries: 5
      delay: 1
      ansible.builtin.uri:
        url: "http://localhost:3000/login"
        return_content: true
        status_code: 200
        method: GET
