---
global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'
  repeat_interval: 9000h
  group_by: [...]
  group_interval: 1m  # set rule flushing interval (resolved won't be updated until next flushing occurs)

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#monitoring'
        send_resolved: true
        icon_url: https://avatars3.githubusercontent.com/u/3380462
        title: '[{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}'
        # fallback is used for notification previews on mobile
        # don't change quotes
        fallback: '[{{ .Status | toUpper }}] {{ range .Alerts -}} {{ .Annotations.title | reReplaceAll "[\\*`]" "" }} {{ end }}'
        text: >-
          {{ range .Alerts -}}
          {{ .Labels.severity | toUpper }} {{ .Annotations.title }}

          {{ if .Annotations.description }}
          *Description:* {{ .Annotations.description }}
          {{ end }}
          {{ end }}
