{
 "title": "genlab-1c",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "gf_nodename", "query": "genlab-1c" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds * on(instance) group_left (nodename) node_uname_info{nodename=\"${gf_nodename}\"} -\nnode_boot_time_seconds * on(instance) group_left (nodename) node_uname_info{nodename=\"${gf_nodename}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kernel",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_uname_info{nodename=\"${gf_nodename}\"}",
     "legendFormat": "{{release}}"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_vmstat_pgmajfault[$__rate_interval]) * on(instance) group_left (nodename) node_uname_info{nodename=\"${gf_nodename}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "rootfs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\"} * on(instance) group_left (nodename) node_uname_info{nodename=\"${gf_nodename}\"}"
    }
   ]
  },
  {
   "type": "gauge",
   "description": "rootfs available bytes",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_avail_bytes{mountpoint=\"/\"} * on(instance) group_left (nodename) node_uname_info{nodename=\"${gf_nodename}\"}) / \n(node_filesystem_size_bytes{mountpoint=\"/\"} * on(instance) group_left (nodename) node_uname_info{nodename=\"${gf_nodename}\"})"
    }
   ]
  },
  { "title": "Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU Load",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum by (cpu)(rate(node_cpu_seconds_total{mode!=\"idle\"}[30s]) * on(instance) group_left (nodename) node_uname_info{nodename=\"${gf_nodename}\"}))"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Σ Threads ",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"system\"} * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"})"
    }
   ]
  },
  {
   "type": "stat",
   "description": "RAM Avail",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"}"
    }
   ]
  },
  {
   "title": "RAM Load",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 10, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - \n(node_memory_MemAvailable_bytes * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"}) / \n(node_memory_MemTotal_bytes * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"})"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "μ Thread Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by (mode, instance) (avg by (mode, instance) (rate(node_cpu_seconds_total{mode!=\"idle\"}[2m]))) * 100) * on(instance) group_left (nodename) node_uname_info{nodename=\"${gf_nodename}\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU Load 1m",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "node_load1 * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_procs_running * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"}",
     "legendFormat": "running"
    },
    {
     "expr": "node_procs_blocked * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"}",
     "legendFormat": "blocked"
    }
   ]
  },
  { "title": "Networking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8 * irate(node_network_receive_bytes_total{device!~\"veth.*|docker.*|lo|ifb.*|br.*\"}[$__rate_interval]) * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"}",
     "legendFormat": "{{device}}: received"
    },
    {
     "expr": "8 * irate(node_network_transmit_bytes_total{device!~\"veth.*|docker.*|lo|ifb.*|br.*\"}[$__rate_interval]) * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"}",
     "legendFormat": "{{device}}: transmit"
    }
   ]
  },
  {
   "title": "Ping Extranet",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ping_rtt_mean_seconds{nodename=\"$gf_nodename\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "RAM Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - \n(node_memory_MemAvailable_bytes * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"}) / \n(node_memory_MemTotal_bytes * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"})",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "RAM Pressure a.k.a. Major page faults (vmstat)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "rate(node_vmstat_pgmajfault[$__rate_interval]) * on(instance) group_left (nodename) node_uname_info{nodename=\"${gf_nodename}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk Space Free, %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(node_filesystem_free_bytes{mountpoint!~\"/run.*|/mnt/.*|/boot/efi|/var/lib/docker.*\"} * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"}) /\n(node_filesystem_size_bytes{mountpoint!~\"/run.*|/mnt/.*|/var/lib/docker.*\"} * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Inodes Available, %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_filesystem_files_free{mountpoint=\"/\"} * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"}) /\n(node_filesystem_files{mountpoint=\"/\"} * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"}) * 100",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "(node_filesystem_files_free{mountpoint=\"/storage\"} * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"}) /\n(node_filesystem_files{mountpoint=\"/storage\"} * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"}) * 100",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "(rate(node_disk_write_time_seconds_total{device=\"vda\"}[$__rate_interval]) * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"}) / \n(rate(node_disk_writes_completed_total{device=\"vda\"}[$__rate_interval]) * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"})",
     "legendFormat": "{{device}}: read"
    },
    {
     "expr": "(rate(node_disk_read_time_seconds_total{device=\"vda\"}[$__rate_interval]) * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"}) / \n(rate(node_disk_reads_completed_total{device=\"vda\"}[$__rate_interval]) * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"})",
     "legendFormat": "{{device}}: write"
    },
    {
     "expr": "rate(node_disk_io_time_seconds_total{device=\"vda\"}[$__rate_interval]) * on(instance) group_left (nodename) node_uname_info{nodename=~\"genlab-1c\"}",
     "legendFormat": "{{device}}: io_time"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{device=\"vda\"}[$__rate_interval]) * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"}",
     "legendFormat": "{{device}}: write"
    },
    {
     "expr": "rate(node_disk_read_bytes_total{device=\"vda\"}[$__rate_interval]) * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"}",
     "legendFormat": "{{device}}: read"
    }
   ]
  }
 ]
}