{
 "title": "genlab-sc",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "gf_nodename", "query": "genlab-sc" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_time_seconds * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"}) - \n(node_boot_time_seconds * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kernel",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_uname_info{nodename=\"${gf_nodename}\"}",
     "legendFormat": "{{release}}"
    }
   ]
  },
  {
   "title": "🌡️ Alarm",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_alarm * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EDAC Corr",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_edac_correctable_errors_total * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EDAC Unc",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_edac_uncorrectable_errors_total * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_vmstat_pgmajfault[$__rate_interval]) * on(instance) group_left (nodename) node_uname_info{nodename=\"${gf_nodename}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "rootfs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\"} * on(instance) group_left (nodename) node_uname_info{nodename=\"${gf_nodename}\"}"
    }
   ]
  },
  {
   "type": "gauge",
   "description": "rootfs available bytes",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_avail_bytes{mountpoint=\"/\"} * on(instance) group_left (nodename) node_uname_info{nodename=\"${gf_nodename}\"}) / \n(node_filesystem_size_bytes{mountpoint=\"/\"} * on(instance) group_left (nodename) node_uname_info{nodename=\"${gf_nodename}\"})"
    }
   ]
  },
  {
   "title": "/home",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/home\"} * on(instance) group_left (nodename) node_uname_info{nodename=\"${gf_nodename}\"}"
    }
   ]
  },
  {
   "type": "gauge",
   "description": "/home available bytes",
   "gridPos": { "h": 3, "w": 2, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_avail_bytes{mountpoint=\"/home\"} * on(instance) group_left (nodename) node_uname_info{nodename=\"${gf_nodename}\"}) / \n(node_filesystem_size_bytes{mountpoint=\"/home\"} * on(instance) group_left (nodename) node_uname_info{nodename=\"${gf_nodename}\"})"
    }
   ]
  },
  { "title": "Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU Load",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum by (cpu)(rate(node_cpu_seconds_total{mode!=\"idle\"}[30s]) * on(instance) group_left (nodename) node_uname_info{nodename=\"${gf_nodename}\"}))"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Σ Threads ",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"system\"} * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"})"
    }
   ]
  },
  {
   "type": "stat",
   "description": "RAM Available",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Load",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 10, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - \n(node_memory_MemAvailable_bytes * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"}) / \n(node_memory_MemTotal_bytes * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"})"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Swap Available",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapFree_bytes * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 10, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (node_memory_SwapFree_bytes * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"}) / \n(node_memory_SwapTotal_bytes * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"})"
    }
   ]
  },
  { "title": "CPU Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "μ Thread Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by (mode, instance) (avg by (mode, instance) (rate(node_cpu_seconds_total{mode!=\"idle\"}[2m]))) * 100) * on(instance) group_left (nodename) node_uname_info{nodename=\"${gf_nodename}\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU Load (1m)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "node_load1 * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"}",
     "legendFormat": "load 1m"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_procs_running * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"}",
     "legendFormat": "running"
    },
    {
     "expr": "node_procs_blocked * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"}",
     "legendFormat": "blocked"
    }
   ]
  },
  {
   "title": "CPU Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Throttling Rate (times)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "rate(node_cpu_core_throttles_total[$__rate_interval]) * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"}",
       "legendFormat": "{{package}}:{{core}}"
      }
     ]
    },
    {
     "title": "CPU Scaling",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "hertz" } },
     "targets": [
      {
       "expr": "node_cpu_scaling_frequency_hertz * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"}",
       "legendFormat": "{{cpu}}"
      }
     ]
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "RAM Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - \n(node_memory_MemAvailable_bytes * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"}) / \n(node_memory_MemTotal_bytes * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"})",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "Swap Free",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(node_memory_SwapFree_bytes * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"}) / \n(node_memory_SwapTotal_bytes * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"})",
     "legendFormat": "swap"
    }
   ]
  },
  {
   "title": "RAM Pressure (Major page faults)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "rate(node_vmstat_pgmajfault[$__rate_interval]) * on(instance) group_left (nodename) node_uname_info{nodename=\"${gf_nodename}\"}",
     "legendFormat": "pgmajfault"
    }
   ]
  },
  {
   "title": "RAM Pressure (Procs stalled / waiting)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_pressure_memory_stalled_seconds_total[$__rate_interval]) * on(instance) group_left (nodename) node_uname_info{nodename=\"${gf_nodename}\"}",
     "legendFormat": "stalled"
    },
    {
     "expr": "rate(node_pressure_memory_waiting_seconds_total[$__rate_interval]) * on(instance) group_left (nodename) node_uname_info{nodename=\"${gf_nodename}\"}",
     "legendFormat": "waiting"
    }
   ]
  },
  { "title": "Memory (by User CGroups)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "RAM Consumption per User CGroup, %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "cgrpuser_exporter_memory_anonymous{nodename=\"genlab-sc\"} / on() group_left() (node_memory_MemTotal_bytes * on(instance) group_left(nodename) node_uname_info{nodename=\"genlab-sc\"}) * 100",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "RAM Consumption per User CGroup, abs.",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cgrpuser_exporter_memory_anonymous{nodename=\"genlab-sc\"}",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Swap Consumption per User CGroup, %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "cgrpuser_exporter_swap_current{nodename=\"genlab-sc\"} / on() group_left() (node_memory_SwapTotal_bytes * on(instance) group_left(nodename) node_uname_info{nodename=\"genlab-sc\"}) * 100",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Swap Consumption per User CGroup, abs.",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cgrpuser_exporter_swap_current{nodename=\"${gf_nodename}\"}",
     "legendFormat": "{{username}}"
    }
   ]
  },
  { "title": "Networking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8 * irate(node_network_receive_bytes_total{device!~\"veth.*|docker.*|lo|ifb.*\"}[$__rate_interval]) * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"}",
     "legendFormat": "{{device}}: rx"
    },
    {
     "expr": "8 * irate(node_network_transmit_bytes_total{device!~\"veth.*|docker.*|lo|ifb.*\"}[$__rate_interval]) * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"}",
     "legendFormat": "{{device}}: tx"
    }
   ]
  },
  {
   "title": "Ping Extranet",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ping_rtt_mean_seconds{nodename=\"${gf_nodename}\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Disk Space Free, %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(node_filesystem_avail_bytes{mountpoint!~\"/run.*|/var/lib/docker.*\"} * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"}) /\n(node_filesystem_size_bytes{mountpoint!~\"/run.*|/var/lib/docker.*\"} * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Inodes Available",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((node_filesystem_files_free{mountpoint=\"/\"} * on (instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"}) / (node_filesystem_files{mountpoint=\"/\"} * on (instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"})) * 100",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "((node_filesystem_files_free{mountpoint=\"/home\"} * on (instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"}) / (node_filesystem_files{mountpoint=\"/home\"} * on (instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"})) * 100",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "SSD Wear",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "smartctl_device_available_spare{device=\"nvme0\", nodename=\"${gf_nodename}\"}",
     "legendFormat": "{{device}}: spare"
    },
    {
     "expr": "100 - smartctl_device_percentage_used{device=\"nvme0\", nodename=\"${gf_nodename}\"}",
     "legendFormat": "{{device}}: write used"
    }
   ]
  },
  {
   "title": "Crit Warn",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_critical_warning{device=\"nvme0\", nodename=\"${gf_nodename}\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Log Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 105 },
   "targets": [
    {
     "expr": "smartctl_device_num_err_log_entries{device=\"nvme0\", nodename=\"${gf_nodename}\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Media Err",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_media_errors{device=\"nvme0\", nodename=\"${gf_nodename}\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 111 },
   "targets": [
    {
     "expr": "(rate(node_disk_write_time_seconds_total[$__rate_interval]) * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"}) / \n(rate(node_disk_writes_completed_total[$__rate_interval]) * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"})",
     "legendFormat": "{{device}}: read"
    },
    {
     "expr": "(rate(node_disk_read_time_seconds_total[$__rate_interval]) * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"}) / \n(rate(node_disk_reads_completed_total[$__rate_interval]) * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"})",
     "legendFormat": "{{device}}: write"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{device=\"nvme0n1\"}[$__rate_interval]) * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"}",
     "legendFormat": "{{device}}: write"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{device=\"sda\"}[$__rate_interval]) * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"}",
     "legendFormat": "{{device}}: write"
    },
    {
     "expr": "rate(node_disk_read_bytes_total{device=\"nvme0n1\"}[$__rate_interval]) * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"}",
     "legendFormat": "{{device}}: read"
    },
    {
     "expr": "rate(node_disk_read_bytes_total{device=\"sda\"}[$__rate_interval]) * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"}",
     "legendFormat": "{{device}}: read"
    }
   ]
  },
  {
   "title": "Sensors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 123 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Core Temperature 🌡️",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{chip!~\"nvme.*|therm.*\"} * on(instance) group_left(nodename) node_uname_info{nodename=\"${gf_nodename}\"}",
     "legendFormat": "{{chip}}:{{sensor}}"
    }
   ]
  }
 ]
}