{
 "title": "genlab-sc.docker",
 "tags": [
  "cadvisor",
  "docker"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{name!=\"\", nodename=\"genlab-sc\"}[$__rate_interval])) by (nodename, name) * 100)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Core-wise",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{name!=\"\", nodename=\"genlab-sc\"}[$__rate_interval])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc((sum(rate(container_cpu_usage_seconds_total{name!=\"\", nodename=\"genlab-sc\"}[$__rate_interval])) by (instance, name) * 100))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{name!=\"\", nodename=\"genlab-sc\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Aggregate",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 2, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{name!=\"\", nodename=\"genlab-sc\"}) / ignoring(instance, job, nodename) (node_memory_MemTotal_bytes * on(instance) group_left(nodename) node_uname_info{nodename=\"genlab-sc\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(container_memory_rss{name!=\"\", nodename=\"genlab-sc\"}) by (name))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{name!=\"\", nodename=\"genlab-sc\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cnexporter_containers_running{nodename=\"genlab-sc\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Created",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cnexporter_containers_created{nodename=\"genlab-sc\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exited",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cnexporter_containers_exited{nodename=\"genlab-sc\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container metadata",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "cnexporter_containers_metadata{nodename=\"genlab-sc\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}